apiVersion: v1.1
resources:
  - name: gitJfrogPipelinesImage
    type: GitRepo
    configuration:
      gitProvider: githubAccountGeoffwilliams
      path: declarativesystems/jfrog-pipelines-image

pipelines:
  - name: jfrogPipelinesImage
    steps:
      - name: dockerBuild
        type: DockerBuild
        configuration:
          affinityGroup: jfrogPipelinesImage
          dockerFileLocation: .
          dockerFileName: Dockerfile
          dockerImageName: declarativesystems.jfrog.io/docker/docker-local/pipelines
          dockerImageTag: $(make print_image_tag)-${run_number}
          inputResources:
            - name: gitJfrogPipelinesImage
          integrations:
            - name: artifactory
        execution:
          onStart:
            - cd $res_gitJfrogPipelinesImage_resourcePath
          onFailure:
            - tree -L 4
      - name: dockerPush
        type: DockerPush
        configuration:
          affinityGroup: jfrogPipelinesImage
          targetRepository: docker-local
          integrations:
            - name: artifactory
          inputSteps:
            - name: dockerBuild
