apiVersion: v1.1
resources:
  - name: gitJfrogPipelinesImage
    type: GitRepo
    configuration:
      gitProvider: githubAccountGeoffwilliams
      path: declarativesystems/jfrog-pipelines-image
      branches:
        include: ^{{gitBranch}}$
      cancelPendingRunsOn:
        pullRequestUpdate: true
        newCommit: true
  - name: containerEnvJfrogPipelinesImage
    type: declarativesystems/ContainerEnv
    configuration:
      sourceArtifactory: artifactory

pipelines:
  - name: jfrogPipelinesImage
    configuration:
      retentionPolicy:
        maxAgeDays: 90
        minRuns: 10
      runtime:
        type: image
        image:
          custom:
            name: "declarativesystems.jfrog.io/docker-local/pipelines"
            tag: "0.8.1"
            registry: artifactory
            sourceRepository: docker-local

    steps:
      - name: buildAndPushImages
        type: Bash
        configuration:
          inputResources:
            - name: gitJfrogPipelinesImage
            - name: containerEnvJfrogPipelinesImage
          integrations:
            - name: artifactory
        execution:
          onExecute:
            - cd ${res_gitJfrogPipelinesImage_resourcePath}
            - make image_build
            - make image_push
